name: CoreRoot
description: Core root contract
structs: {}
typedefs: {}
state: {}
funcs:
  deployContract:
    params:
      description=ds: String? // default 'N/A'
      name=nm: String
      programHash=ph: Hash //TODO variable init params for deployed contract
  grantDeployPermission:
    params:
      deployer=dp: AgentID
  revokeDeployPermission:
    params:
      deployer=dp: AgentID
views:
  findContract:
    params:
      hname=hn: Hname
    results:
      contractFound=cf: Bytes // encoded contract record
      contractRecData=dt: Bytes // encoded contract record
  getContractRecords:
    results:
      contractRegistry=r: map[Hname]Bytes // contract records
