version: "3.9"
services:
  wasp:
    build:
      context: ../../
      dockerfile: ./tools/monitoring/Dockerfile
    ports:
      - "2112:2112"
      - "7000:7000"
      - "9090:9090"
      - "5550:5550"
      - "4000:4000"
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9091:9090"
    volumes:
      - .:/etc/prometheus
  grafana:
    build:
      context: ./grafana
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "0"
